### ISSUE TITLE
Incorrect export of `JVM_IO` functions with `do` notation

### ISSUE THREAD

**Issue by alaendle** [mmhelloworld/idris-jvm#83]
Just add the following code to the integration tests...

`module Main

main : IO ()
main = do
  putStrLn "world!"`

and tests will fail with 

> Time elapsed: 180.061 s  <<< ERROR! java.lang.RuntimeException: Compilation timed out.

and empty compiler.log.

**Comment by mmhelloworld** [comment]
Thanks for reporting. It seems like the last release package didn't have the latest `idris-jvm-runtime` jar. I have released a new version to fix that. Your simple program also revealed another issue with how Idris generates a `main` function. The `main` function generated for this program (`main`) is different when we have a non-trivial program (`{runMain_0}`) so the following program works as currently idris-jvm always looks for the second one. Let's keep the issue open to fix the generated `main` function for simple programs.

```
module Main

main : IO ()
main = do
  putStrLn "hello "
  printLn $ length "world!"
```

**Comment by alaendle** [comment]
Thanks for your quick reaction. Might it be the case that the problem you've mentioned also occurs on FFI exports - or might this be another issue?

E.g. my program compiles fine, but during runtime, it throws an.. 

> java.lang.NoSuchMethodError: main.Main.mouseDragged(Ljava/lang/Object;)Lio/github/mmhelloworld/idrisjvm/runtime/IdrisObject;

The generated method has signature `public static IdrisObject mouseDragged(Object var0, Object var1)`, but the exporting class calls this function with only one argument.
`public void mouseDragged() {
        Runtime.unwrap(Main.call__IO((Object)null, (Object)null, Main.mouseDragged(this)));
    }`

But if I simplify the implementation of mouseDragged to a single putStrLn call everything works fine.
I really hope this condensed description of the problem guides you in the right direction; for now I keep short, so please don't hesitate to ask if you need more information.

**Comment by mmhelloworld** [comment]
Hi,

I have fixed the issue with `main` function and uploaded a [new release](https://github.com/mmhelloworld/idris-jvm/releases/tag/v1.0-SNAPSHOT-20181202). Please let me know if you still have that issue. I will look into the export issue.

**Comment by alaendle** [comment]
Hi,
I fear the issue still exists in the newest release. To make things more clear I have attached some sourcecode; everything works if I have only one `printLn` in `mouseDragged `; but if the second `printLn` is included I face error: `java.lang.NoSuchMethodError: main.Main.mouseDragged(Ljava/lang/Object;)Lio/github/mmhelloworld/idrisjvm/runtime/Thunk;`. I hope that's enough for you to reproduce/solve the problem, but don't hesitate to ask for more information.

```
module Main

import IdrisJvm.FFI
import IdrisJvm.IO
import Java.Lang
import Effect.Random
import Effect.System
import Effects

%access public export

IdrisPApplet : Type
IdrisPApplet = JVM_Native $ Class "processing/core/PApplet"

size : IdrisPApplet -> Int -> Int -> JVM_IO ()
size = invokeInstance "size" (IdrisPApplet -> Int -> Int -> JVM_IO ())

background : IdrisPApplet -> Int -> JVM_IO ()
background = invokeInstance "background" (IdrisPApplet -> Int -> JVM_IO ())

settings : IdrisPApplet -> JVM_IO ()
settings this = do
  size this 500 500

mouseDragged : IdrisPApplet -> JVM_IO ()
mouseDragged this =
  do
    printLn "mouseDragged -- 1"
    printLn "mouseDragged -- 2"  -- if you remove this line everything works

draw : IdrisPApplet -> JVM_IO ()
draw this = do
  background this 64

main : IO ()
main = pure ()

exports : FFI_Export FFI_JVM "Idris/JMain extends processing/core/PApplet" []
exports =
  Fun draw (ExportInstance "draw") $
  Fun settings (ExportInstance "settings") $
  Fun mouseDragged (ExportInstance "mouseDragged") $
  End
```

**Comment by mmhelloworld** [comment]
Right, I should have been more clear. I fixed the issue with the following program as in your original post.

```
module Main

main : IO ()
main = do
    putStrLn "world!"
```

As for the issue with the export function, `mouseDragged` in your program, I will have to look into this but I think the following workaround should work:

```
mouseDragged' : IdrisPApplet -> JVM_IO ()
mouseDragged' this =
  do
    printLn "mouseDragged -- 1"
    printLn "mouseDragged -- 2"

mouseDragged: IdrisPApplet -> JVM_IO ()
mouseDragged = mouseDragged'
```

The idea is to add an alias and export that function instead. I have also got this error related to exporting `JVM_IO` functions with `do` notation in the past and this workaround worked for me. Please let me know if this works for you. Let's keep this issue open to fix it properly.

**Comment by alaendle** [comment]
Nearly - your code doesn't work because mouseDragged no longer has any parameter in its java signature.
But the strange thing is that this works...

```
mouseDragged : IdrisPApplet -> JVM_IO ()
mouseDragged this = mouseDragged' this
```

My naive expectation would have been that after the idris compiler has processed the source code, the two implementations are indistinguishable. So maybe this is even something that could be improved in idris? Nonetheless the jvm backend should cope with both notations.

**Comment by mmhelloworld** [comment]
I remembered something along that line. Good that it works for your case as well. This may be something we need to fix in Idris itself but I will see if we can make it work in the JVM back end.

**Comment by mmhelloworld** [comment]
This should now be fixed with #92.

**Comment by mmhelloworld** [comment]
Hi @alaendle ,

It appears to be working fine for me. It seems like you are still compiling with old version of idris-jvm. This is how the generated class looks for me with the latest version:
```
public class JMain extends PApplet {
    public JMain() {
    }

    public void draw() {
        Runtime.unwrap(Main.call__IO((Object)null, (Object)null, Main.draw(this)));
    }

    public void settings() {
        Runtime.unwrap(Runtime.unwrap(Main.settings(this, (Object)null)));
    }

    public void mouseDragged() {
        Runtime.unwrap(Runtime.unwrap(Main.mouseDragged(this, (Object)null)));
    }
}

```
Could you please try with the latest idris-jvm release? Sorry, I couldn't get back to you earlier.

**Comment by alaendle** [comment]
Hi @mmhelloworld ,
mea culpa - to be honest I still couldn't figure out what went wrong; so I deleted all idris related stuff from my PC and re-installed everything from scratch. And now things work as expected and the generated code looks exact like the snippet you have posted. So please excuse the additional unnecessary effort I've created for you. 
To look on the bright side - at least we now have double checked the original issue.
Many thanks for your support!
